name: Test java2typescript

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout sources
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Setup Scala
      uses: olafurpg/setup-scala@v11
      with:
        java-version: openjdk@1.17.0

    - name: Build typescript writer
      working-directory: ./src/main/javascript
      run: npm install

    - name: run test
      run: sbt test
